spring:
    datasource:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: /
        suffix: .html
    thymeleaf:
      cache: false
server:
  port: 8989
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      timeout: 0
ue:
  config-file: static/ueditor/config.json
  server-url: /ueditor.do
  qiniu:
    accessKey: 8Dw03nJLiST7RvsWtPca1JHDgeu8O0BAWsICDLY_
    secretKey: LHkGDHPZCyrUk5BxG7vC5sLY9LmDxfZYerdo3W82
    cdn: http://video.dcssn.com/
    bucket: video
    zone: zone0

